[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Patrick did mention that we consider any test with revert,
# in the data not equal to 0 as failed for now, until the bug is fixed.